### ISSUE TITLE
PyPi badge leads to a different project

### ISSUE THREAD

**Issue by vEpiphyte** [DomainTools/python_api#16]
The pypi badge in the readme links to https://pypi.python.org/pypi/domaintools/ and not https://pypi.python.org/pypi/domaintools_api

This could result in someone installing the wrong package by mistake.

**Comment by vEpiphyte** [comment]
@dlrust @timothycrosley

**Comment by timothycrosley** [comment]
Thanks for reporting this!

I've fixed the link on the README here, and that will reflect withing the PYPI's readme whenever we do the next release.

The other project on PYPI labeled `domaintools` has never had anything uploaded to it, and so is uninstallable. We've had an open ticket with PYPI for about a year to get the name released to us, but they haven't had anyone available for cleaning up unused names in that time span.
