### ISSUE TITLE
ModuleNotFoundError: domaintools_async

### ISSUE THREAD

**Issue by FosterA** [DomainTools/python_api#19]
Using a python virtualenv with python 3.6.5. Following initial setup and ont import of the API I receive this error: 
``` python                                                                                                                                (env: dt_env)
Python 3.6.5 (default, Apr 25 2018, 14:26:36)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from domaintools import API
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/username/Envs/dt_env/lib/python3.6/site-packages/domaintools/__init__.py", line 3, in <module>
    from domaintools.api import API
  File "/Users/username/Envs/dt_env/lib/python3.6/site-packages/domaintools/api.py", line 7, in <module>
    from domaintools.results import GroupedIterable, ParsedWhois, Reputation, Results
  File "/Users/username/Envs/dt_env/lib/python3.6/site-packages/domaintools/results.py", line 19, in <module>
    from domaintools_async import AsyncResults as Results
ModuleNotFoundError: No module named 'domaintools_async'
>>>
``` 

Any additional setup steps needed? Verified that `domaintools-api 0.2.2` is in the output of `pip-list`

**Comment by timothycrosley** [comment]
Hi @FosterA,

I'm sorry you ran into this issue! I'm not sure how exactly this happened, but I have an inclination it has to do with some of the magic done to allow the single module to support async only if installed on Python3: https://github.com/DomainTools/python_api/blob/master/setup.py#L15. My suggestion would be to try to uninstall and reinstall within the environment, potentially with wheel support disabled, and see if it resolves this issue for you. If not please let us know and we will investigate further.

Thanks!

~Timothy
