### ISSUE TITLE
Undefined exception in async

### ISSUE THREAD

**Issue by jnwatson** [DomainTools/python_api#23]
I was just perusing your source code trying to figure out how you guys managed the async transition (excellent hackery, BTW) and I spotted a couple of minor bugs.

You're missing an import of your exceptions file: On https://github.com/DomainTools/python_api/blob/master/domaintools_async/__init__.py#L46 `ServiceUnavailableException` is an undefined name.

(I'll report the other bug separately).

**Comment by timothycrosley** [comment]
I've released version 0.3.0 that includes your fixes and resolves this issue.

Thank you again!

~Timothy
