### ISSUE TITLE
Update asyncio version to 3.x

### ISSUE THREAD

**Issue by jnwatson** [DomainTools/python_api#24]
The current version of aiohttp is 3.4.4. Your setup (https://github.com/DomainTools/python_api/blob/master/setup.py#L16) requires version 2.3.6.

On https://github.com/DomainTools/python_api/blob/master/domaintools_async/__init__.py#L41, you must add an `async` at the beginning of this line, because aiohttp v3 clientSession only accepts async context managers now.

**Comment by jnwatson** [comment]
I'll have a PR up shortly.

**Comment by timothycrosley** [comment]
I've released version 0.3.0 that includes your fixes and resolves this issue.

Thank you again!

~Timothy
