### ISSUE TITLE
Unawaited coroutine

### ISSUE THREAD

**Issue by jnwatson** [DomainTools/python_api#27]
On https://github.com/DomainTools/python_api/blob/master/domaintools_async/__init__.py#L33, response is passed in and the `json` method is called on it here: https://github.com/DomainTools/python_api/blob/master/domaintools/base_results.py#L110

`json` returns a coroutine. It is never awaited.

**Comment by timothycrosley** [comment]
I've released version 0.3.0 that includes your fixes and resolves this issue.

Thank you again!

~Timothy
