### ISSUE TITLE
async calls can block on sync calls made via requests

### ISSUE THREAD

**Issue by vEpiphyte** [DomainTools/python_api#30]
Issue
-----

When reviewing recorded async API calls with VCR, I realized that a request was being made to `https://api.domaintools.com/v1/account` URL prior to performing the requested URL via aiohttp.  This is done for rate limiting.  This request is made with a requests.Session.get() call, which will block the ioloop for the current thread.

A brief call stack is the following:

```
# domaintools python_api code
whois_history, api.py:176
_results, api.py:59
_rate_limit, api.py:53
__iter__, base_results.py:169
_items, base_results.py:152
response, base_results.py:133
data, base_results.py:83
_get_results, base_results.py:65
_make_request, base_results.py:60
# Down into requests.Session code here
get, sessions.py:536
```

Environment
-----------

Python & os:

- Python 3.7.0
- Ubuntu 16.04

Relevant libraries:

- aiohttp==3.4.4
- domaintools-api==0.3.1
- requests==2.20.0
- vcrpy==1.13.0

**Comment by dnunes-domaintools** [comment]
Hi @vEpiphyte, thanks for raising this, and apologies it's taken us so long to get back to you on this! In case it's still relevant or for anyone else looking at this, this is as-designed. This is an artifact of the rate-limiting we have in place.
