### ISSUE TITLE
Python 3.7 ImportError: cannot import name 'API' from 'domaintools' (unknown location)

### ISSUE THREAD

**Issue by wesinator** [DomainTools/python_api#36]
macOS 10.14.6
python 3.7.4 (brew 3.7.4_1)
domaintools-api    0.3.3

```python-traceback
$ domaintools 
Traceback (most recent call last):
  File "/usr/local/bin/domaintools", line 7, in <module>
    from domaintools.cli import run
  File "/usr/local/lib/python3.7/site-packages/domaintools/cli.py", line 7, in <module>
    from domaintools import API
ImportError: cannot import name 'API' from 'domaintools' (unknown location)
```

**Comment by mwilutis** [comment]
i'm also having this issue, same versions

**Comment by wesinator** [comment]
**TL,DR:** fix - uninstall and reinstall domaintools-api
I figured out the issue, this is a conflict with https://github.com/devhub/domaintools/tree/master/domaintools 
https://github.com/devhub/domaintools/issues/9

If you install one after the other, it clobbers since they are installed under the same directory. 

There are two issues happening here:
  - pip doesn't check for package directory conflicts, clobbers the first installed package.
    https://github.com/pypa/pip/issues/7282
  - domaintools-api uses the same dir name as this other domaintools package 
    **TODO for DomainTools:** rename this package dir to `domaintools-api`
