### ISSUE TITLE
exceptions.ServiceException: Unknown Exception

### ISSUE THREAD

**Issue by dwissm1** [DomainTools/python_api#38]
While sending bulk lookups through the IRIS investigate API, I hit an exception in the Unknown Category. (exceptions.ServiceException: Unknown Exception).

 I did some debugging and it looks like the URI is large and I am getting a HTTP Status : 413: Payload Too Large response. (https://tools.ietf.org/html/rfc7231#section-6.5.11) . I have also gotten the 414 URI too long.

Work around is to lessen the amount of domains sent to try to keep it under the limit but ideally, I would love to be able to send 100 at a time to keep it nice a quick.

Thanks for taking a look.

**Comment by arunura** [comment]
@dwissm1 The IRIS investigate API supports both [GET and POST](https://www.domaintools.com/resources/api-documentation/iris-investigate). I believe you should be able to get around the URL length issues by using POST. 

If you are using the python_api, it seems to use [POST internally](https://github.com/DomainTools/python_api/blob/master/domaintools/base_results.py#L64).
