### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by paperplanes123** [DomainTools/python_api#60]
I keep getting this:  "from: can't read /var/mail/domaintools"

**Comment by jmeridth** [comment]
Thank you for filing an issue.

What version of this library are you using?
What call were you making exactly? Can you elaborate a little on your specific scenario?

Thank you.

**Comment by jmeridth** [comment]
@paperplanes123 any update on this?

**Comment by jmeridth** [comment]
@paperplanes123 closing this issue.  If you update, we can reopen.
