### ISSUE TITLE
Bug: Limit Check for XML

### ISSUE THREAD

**Issue by malvidin** [DomainTools/python_api#79]
Line 117 in base_results.py should be `limit_exceeded`, not `limit_exdeeded`.  The limit check will fail if the format is not JSON (unless the spelling in the JSON and XML responses differ).
https://github.com/DomainTools/python_api/blob/86959fb0fe96b798e2599eb5978a45aeb159bd2c/domaintools/base_results.py#L117

**Comment by mccarthym** [comment]
Thank you for the comment @malvidin, this oversight has been addressed.
